import { Ubuntu } from 'next/font/google';
import Navbar from "@/components/reuseables/navbar/Navbar";
import "./globals.css";
import Footer from "@/components/reuseables/footer/Footer";
import { ToastContainer } from 'react-toastify';

export const metadata = {
  title: "MechVacc",
  description: "Generated by create next app",
};

const ubuntu = Ubuntu({
  weight: ['400', '500', '700'], 
  subsets: ['latin'], 
  display: 'swap', 
});

interface RootLayoutProps {
  children: React.ReactNode;
}

export default function RootLayout({ children }: RootLayoutProps) {
  
  // Use environment variable for maintenance mode
   const maintenanceMode = process.env.NEXT_PUBLIC_MAINTENANCE_MODE === 'true';

  return (
    <html lang="en">
      <body className={`${ubuntu.className} antialiased`}>
        {/* Only show Navbar if not in maintenance mode or not on maintenance page */}
        { !maintenanceMode && <Navbar />}
        {children}  
        <ToastContainer position="top-right" autoClose={5000} />
        {/* Only show Footer if not in maintenance mode or not on maintenance page */}
        { !maintenanceMode && <Footer />}
      </body>
    </html>
  );
}