import { Ubuntu } from 'next/font/google';
import Navbar from "@/components/reuseables/navbar/Navbar";
import "./globals.css";
import Footer from "@/components/reuseables/footer/Footer";

export const metadata = {
  title: "MechVacc",
  description: "Generated by create next app",
};

const ubuntu = Ubuntu({
  weight: ['400', '500', '700'], 
  subsets: ['latin'], 
  display: 'swap',    // 'swap' avoids invisible text during font loading
});

interface RootLayoutProps {
  children: React.ReactNode;
}

export default function RootLayout({ children }: RootLayoutProps) {
  return (
    <html lang="en">
      <body className={`${ubuntu.className} antialiased`}>
        <Navbar/>
        {children}  
        <Footer/>
      </body>
    </html>
  );
}
